# Generated by Django 5.1.6 on 2025-02-18 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='təlimlər',
            old_name='bootcamp_type',
            new_name='bootcamp_tipi',
        ),
    ]
