# Generated by Django 5.1.6 on 2025-02-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_bootcamp_type_təlimlər_bootcamp_tipi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootcamps',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bootcamptipi',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='təlimlər',
            name='order',
            field=models.IntegerField(),
        ),
    ]
